# env:
env_config:
  env_name: SweetHome3D
taskset_name: HF-PGM

observation_shapes: 
  image_hsr_256: [3, 256, 256]
  Pose: [4]

action_name: "action" # Pose or action(dummy)
action_size: 4      # 4 or 1(dummy)
action_repeat: 1
bit_depth: 5
max_episode_length: 
