version: "2.4"

################################################################################

services:
  turtlebot3:
    hostname: HF-PGM
    runtime: ${DOCKER_RUNTIME}
    privileged: true
#    container_name: otakeshunsuke_hf-pgm_turtlebot3_2
    environment:
      # Display X Server GUIs.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # Configure the Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=11.2.2
      - DOCKER_RUNTIME=${DOCKER_RUNTIME}
      # Configure the PulseAudio interface.
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    image: otake_hf-pgm_turtlebot3-devel:latest
    build:
      context: ../
      dockerfile: ./docker/turtlebot3-devel/Dockerfile
      args: 
        - DOCKERFILE_COMMIT_SHORT_SHA
    # user: root
    volumes:
      # Map repository root for convenient access.
      - ../:/root/TurtleBot3/
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Grant audio access to PulseAudio.
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    # Use 'network_mode: host' with the real robot or 'network_mode: bridge' for separated networks (multiple independent containers).
    network_mode: host
    command: /root/TurtleBot3/docker/turtlebot3-devel/scripts/initialize-docker-container.bash
