version: "2.4"

################################################################################

services:
  hsr:
    hostname: hsr
    runtime: ${DOCKER_RUNTIME}
    privileged: true
    environment:
      # Display X Server GUIs.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # Configure the Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=10.1
      - DOCKER_RUNTIME=${DOCKER_RUNTIME}
      # Configure the PulseAudio interface.
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    image: registry.hsr.io/sdewg/hsr/hsr-devel:latest
    build:
      context: ../
      dockerfile: ./docker/hsr-devel/Dockerfile
      args: 
        - DOCKERFILE_COMMIT_SHORT_SHA
    volumes:
      # Map repository root for convenient access.
      - ../:/root/HSR/
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Grant audio access to PulseAudio.
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    # Use 'network_mode: host' with the real robot or 'network_mode: bridge' for separated networks (multiple independent containers).
    network_mode: host
    command: /root/HSR/docker/hsr-devel/scripts/initialize-docker-container.bash
