free_thresh: 0.196
image: /root/TurtleBot3/catkin_ws/src/sde_launch/config/gazebo/maps/aws_robomaker_small_house_world/map.pgm
negate: 0
occupied_thresh: 0.65
origin:
- -51.224998
- -51.224998
- 0.0
resolution: 0.05
