# Documentation for configuration of GitLab CI jobs with 'gitlab-ci.yml':
# https://docs.gitlab.com/ee/ci/yaml/
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#limitations-of-docker-in-docker

# See 'SETUP-GITLAB-RUNNER.bash' for the runner configuration details.

################################################################################

# Define the pipeline stages.
# https://docs.gitlab.com/ee/ci/yaml/#stage

stages:
  - build-stage
  - test-stage
  - deploy-stage

################################################################################

# Define the common configuration of all jobs.

# Use Docker-in-Docker with TLS disabled in the Docker executor.
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-disabled-in-the-docker-executor
image: docker:20.10.11
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
services:
  - docker:20.10.11-dind
before_script:
  - docker info

################################################################################

# Build the Catkin workspace inside a Docker container instance of the 'turtlebot3-devel' image.

build-catkin-workspace-job:
  stage: build-stage
  script:
    - docker run -e CI=${CI} ${CI_REGISTRY_IMAGE}/turtlebot3-devel:latest /root/TurtleBot3/docker/turtlebot3-devel/scripts/reset-catkin-workspace.bash
